const ACTION_TYPE = {
	LIST_VIDEO_LOADED: "LIST_VIDEO_LOADED",
	LIST_VIDEO_FAILED: "LIST_VIDEO_FAILED",
	AUTOPLAY_ON : "AUTOPLAY_ON",
	AUTOPLAY_OFF : "AUTOPLAY_OFF",
	SELECT_VIDEO : "SELECT_VIDEO"
}

export default ACTION_TYPE;

